apiVersion: v1
kind: Service
metadata:
  name: wealthwatch
  namespace: wealthwatch
spec:
  selector:
    app: wealthwatch
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
