apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wealthwatch
resources:
  - namespace.yaml
  - app-configmap.yaml
  - app-secret.yaml
  - postgres.yaml
  - app-deployment.yaml
  - app-service.yaml
  - app-ingress.yaml
